apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: kube-ops
  labels:
    name: gitlab
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 30008
      targetPort: http
    - name: ssh
      port: 22
      nodePort: 30007
      targetPort: ssh
    - name: prometheus
      port: 9090
      targetPort: prometheus
  selector:
    name: gitlab
